cart/urls.py
from django.urls import path
from .import views
app_name='cart'

urlpatterns=[
path('add/<int:product_id>/',views.add_cart,name="add_cart"),
path('',views.cart_detail,name="cart_detail"),
path('cart_remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
path('full_remove/<int:product_id>/',views.full_remove,name="full_remove"),



]

homepage/urls.py
from django.urls import path
from homepage import views
app_name='homepage'

urlpatterns=[
 path('',views.home,name='home')
]

myfashion/urls.py
from django.contrib import admin
from django.urls import path,include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/',include('homepage.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('category/',include('category.urls')),
    path('product/',include('product.urls')),
    path('account/create/',views.signupView,name='signup'),
    path('account/login/',views.signinView,name='signin'),
    path('account/logout/',views.signoutView,name='signout'),
    


]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.
from homepage.models import Product

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    Quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.Quantity
    def __str__(self):
        return self.product

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from homepage.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
import stripe
from django.conf import settings
from order.models import Order, OrderItem

# Create your views here.
def _cart_id(request):
  cart=request.session.session_key
  if not cart:
      cart=request.session.create()
  return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
         cart_item=CartItem.objects.get(product=product,cart=cart)
         if cart_item.Quantity<cart_item.product.stock:
            cart_item.Quantity += 1
         cart_item.save()
    except CartItem.DoesNotExist:
         cart_item=CartItem.objects.create(product=product,Quantity=1,cart=cart)
         cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.Quantity)
            counter +=cart_item.Quantity
    except ObjectDoesNotExist:
        pass

    stripe.api_key= settings.STRIPE_SECRET_KEY
    stripe_total=int(total*100)
    description='clothing ordering shop'
    data_key = settings.STRIPE_PUBLISHABLE_KEY
    if request.method =='POST':
        try:
            token = request.POST['stripeToken']
            email = request.POST['stripeEmail']
            token = request.POST['stripeToken']
            billingName=request.POST['stripeBillingName']
            billingAddress1=request.POST['stripeBillingAddressLine1']
            billlingCity=request.POST['stripeBillingAddressCity']
            billingPostcode=request.POST['stripeBillingAddressZip']
            billingCountry=request.POST['stripeBillingAddressCountryCode']
            shippingName=request.POST['stripeShippingName']
            shippingAddress1=request.POST['stripeShippingAddressLine1']
            shippingCity=request.POST['stripeShippingAddressCity']
            shippingPostcode=request.POST['stripeShippingAddressZip']
            shippingCountry=request.POST['stripeShippingAddressCountryCode']
            customer = stripe.Customer.create(email=email,source=token)
            charge =stripe.Charge.create(amount=stripe_total,currency="gbp",description=description,customer=customer.id)
            try:
                order_details=Order.objects.create(token=token,total=total,emailAddress=email,billingName=billingName,billingAddress1=billingAddress1,billlingCity=billlingCity,billingPostcode=billingPostcode,
                             billingCountry=billingCountry,shippingName=shippingName,shippingAddress1=shippingAddress1,shippingCity=shippingCity,shippingPostcode=shippingPostcode,shippingCountry=shippingCountry)

                order_details.save()
                for order_item in cart_items:
                    oi=OrderItem.objects.create(
                        product=order_item.product.name,
                        quantity=order_item.Quantity,
                        price=order_item.product.price,
                        order=order_details
                    )
                    oi.save()
                    products=Product.objects.get(id=order_item.product.id)
                    products.stock=int(order_item.product.stock - order_item.Quantity)
                    products.save()
                    order_item.delete()
                    print('the order has been created')
                return redirect('order:thanks',order_details.id)
            except ObjectDoesNotExist:
               pass
        except stripe.error.CardError as e:
               return False,e
    return render(request,'Cart.html', dict(cart_items=cart_items,total=total,counter=counter, data_key= data_key, stripe_total=stripe_total,description=description))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.Quantity >1:
       cart_item.Quantity -=1
       cart_item.save()

    else:
       cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

cart/templates/Cart.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
      This is the shopping cart page. Proceed to review your items and place the ordering
{% endblock %}
{% block title %}
    Cart - Himalaya collection
{% endblock %}
{% block css_custums %}
<link rel="stylesheet" type="text/css" href="{% static  'css/cart.css' %}">
<link rel="stylesheet" type="text/css" href="{% static  'css/cart_responsive.css' %}">
<link rel="stylesheet" type="text/css" href="styles/cart.css">
<link rel="stylesheet" type="text/css" href="styles/cart_responsive.css">
{% endblock %}

{% block content %}

<div class="home">
  <div class="home_container d-flex flex-column align-items-center justify-content-end">
    <div class="home_content text-center">
      <div class="home_title">Shopping Cart</div>
      <div class="breadcrumbs d-flex flex-column align-items-center justify-content-center">
        <ul class="d-flex flex-row align-items-start justify-content-start text-center">
          <li><a href="{% url 'homepage:home' %}">Home</a></li>
          <li>Your Cart</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<!-- Cart -->

<div class="cart_section">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="cart_container">

          <!-- Cart Bar -->

          <div class="cart_bar">
            <ul class="cart_bar_list item_list d-flex flex-row align-items-center justify-content-end">
              <li class="mr-auto">Product</li>
              <li>Color</li>
              <li>Size</li>
              <li>Price</li>
              <li>Quantity</li>
              <li>Total</li>
            </ul>
          </div>

          <!-- Cart Items -->
          <div class="cart_items">
            <ul class="cart_items_list">

              <!-- Cart Item -->
              {% for cart_item in cart_items %}
              <li class="cart_item item_list d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-lg-end justify-content-start">
                <div class="product d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start mr-auto">
                  <div><div class="product_number">1</div></div>
                  <div><div class="product_image"><img src="{{cart_item.product.image.url}}" alt=""></div></div>
                  <div class="product_name_container">
                    <div class="product_name"><a href="product.html">{{cart_item.product.name}}</a></div>
                    <div class="product_text">Second line for additional info</div>
                  </div>
                </div>
                <div class="product_color product_text"><span>Color: </span>beige</div>
                <div class="product_size product_text"><span>Size: </span>{{cart_item.product.size}}</div>
                <div class="product_price product_text"><span>Price: </span>${{cart_item.product.price}}</div>
                <!--test -->

                <div class="product_quantity_container">
                  <div class="product_quantity ml-lg-auto mr-lg-auto text-center">
                    <span class="product_text product_num">{{cart_item.Quantity}}</span>

                    {% if cart_item.Quantity < cart_item.product.stock %}
                  <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a">
                      <div class="qty_add qty_button trans_200 text-center"><span>+</span></div></a>&nbsp;
                      <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                      <div class="qty_sub qty_button trans_200 text-center"><span>-</span></div></a>&nbsp;
                      <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon">
                      <i class="fas fa-trash-alt custom_icon"></i></a>
                      </td>
                      {% else %}

                       <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                    <div class="qty_sub qty_button trans_200 text-center"><span>-</span></div></a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon">
                      <i class="fas fa-trash-alt custom_icon"></i></a>
                      </td>

                      {% endif %}
                    <!--code -->

                  </div>
                </div>
                <div class="product_total product_text"><span>Total: </span>Qty:{{cart_item.Quantity}} x ${{cart_item.product.price}}</div>
              </li>


{% endfor %}

            </ul>
          </div>

          <!-- Cart Buttons -->
          <div class="cart_buttons d-flex flex-row align-items-start justify-content-start">
            <div class="cart_buttons_inner ml-sm-auto d-flex flex-row align-items-start justify-content-start flex-wrap">
              <div class="button button_clear trans_200"><a href="categories.html">clear cart</a></div>
              <div class="button button_continue trans_200"><a href="{% url 'homepage:home' %}">continue shopping</a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row cart_extra_row">
      <div class="col-lg-6">
        <div class="cart_extra cart_extra_1">
          <div class="cart_extra_content cart_extra_coupon">
            <div class="cart_extra_title">Coupon code</div>
            <div class="coupon_form_container">
              <form action="#" id="coupon_form" class="coupon_form">
                <input type="text" class="coupon_input" required="required">
                <button class="coupon_button">apply</button>
              </form>
            </div>
            <div class="coupon_text">updating soon </div>
            <div class="shipping">
              <div class="cart_extra_title">Shipping Method</div>
              <ul>
                <li class="shipping_option d-flex flex-row align-items-center justify-content-start">
                  <label class="radio_container">
                    <input type="radio" id="radio_1" name="shipping_radio" class="shipping_radio">
                    <span class="radio_mark"></span>
                    <span class="radio_text">Next day delivery</span>
                  </label>
                  <div class="shipping_price ml-auto">$4.99</div>
                </li>
                <li class="shipping_option d-flex flex-row align-items-center justify-content-start">
                  <label class="radio_container">
                    <input type="radio" id="radio_2" name="shipping_radio" class="shipping_radio">
                    <span class="radio_mark"></span>
                    <span class="radio_text">Standard delivery</span>
                  </label>
                  <div class="shipping_price ml-auto">$1.99</div>
                </li>
                <li class="shipping_option d-flex flex-row align-items-center justify-content-start">
                  <label class="radio_container">
                    <input type="radio" id="radio_3" name="shipping_radio" class="shipping_radio" checked>
                    <span class="radio_mark"></span>
                    <span class="radio_text">Personal Pickup</span>
                  </label>
                  <div class="shipping_price ml-auto">Free</div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 cart_extra_col">
        <div class="cart_extra cart_extra_2">
          <div class="cart_extra_content cart_extra_total">
            <div class="cart_extra_title">Cart Total</div>
            <ul class="cart_extra_total_list">
            <!--  <li class="d-flex flex-row align-items-center justify-content-start">
                <div class="cart_extra_total_title">Subtotal</div>
                <div class="cart_extra_total_value ml-auto">Unit Price:${{cart_item.product.price}}</div>
              </li>-->
              <li class="d-flex flex-row align-items-center justify-content-start">
                <div class="cart_extra_total_title">Shipping</div>
                <div class="cart_extra_total_value ml-auto">Free</div>
              </li>
              <li class="d-flex flex-row align-items-center justify-content-start">
                <div class="cart_extra_total_title">Total</div>
                <div class="cart_extra_total_value ml-auto">${{total}}</div>
              </li>
            </ul>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;





            <form action="" method="POST" style="float:center;">
              {% csrf_token %}
<script
src="https://checkout.stripe.com/checkout.js" class="stripe-button checkout_button trans_200"
data-key="{{data_key}}"
data-amount="{{stripe_total}}"
data-name="myfashion"
data-description="{{description}}"
data-image="{% static 'img/logo.jpg' %}"
data-locale="auto"
data-currency="gbp"
data-shipping-address="True"
data-billing-address="True"
data-zip-code="true">>
</script>
</form>


          <!--  <div class="checkout_button trans_200"><a href='../order'>proceed to checkout</a></div> --->

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  {% endblock %}