cart/urls.py
from django.urls import path
from .import views
app_name='cart'

urlpatterns=[
path('add/<int:product_id>/',views.add_cart,name="add_cart"),
path('',views.cart_detail,name="cart_detail"),
path('cart_remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
path('full_remove/<int:product_id>/',views.full_remove,name="full_remove"),



]

category/urls.py
from django.urls import path
from category import views
app_name='category'

urlpatterns=[
 path('',views.getAllCat,name='category'),
 path('<slug:catname>',views.prodByCat,name='products_by_category'),
 ]

homepage/urls.py
from django.urls import path
from homepage import views
app_name='homepage'

urlpatterns=[
 path('',views.home,name='home')
]

myfashion/urls.py
from django.contrib import admin
from django.urls import path,include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/',include('homepage.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('category/',include('category.urls')),
    path('product/',include('product.urls')),
    path('account/create/',views.signupView,name='signup'),
    path('account/login/',views.signinView,name='signin'),
    path('account/logout/',views.signoutView,name='signout'),
    


]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from .import views
app_name='search_app'

urlpatterns=[
path('',views.searchResult,name="searchResult"),
]

homepage/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
      name=models.CharField(max_length=250,unique=True)
      slug=models.SlugField(max_length=250,unique=True)
      description=models.TextField(blank=True)
      image=models.ImageField(upload_to='category',blank=True)

      class Meta:
           ordering=('name',)
           verbose_name='category'
           verbose_name_plural='categories'

      def get_url(self):
          return reverse('homepage:products_by_category',args=[self.slug])
      def __str__(self):
          return self.name

class Product(models.Model):
      name=models.CharField(max_length=250,unique=True)
      slug=models.SlugField(max_length=250,unique=True)
      description=models.TextField(blank=True)
      category=models.ForeignKey(Category,on_delete=models.CASCADE)
      price=models.DecimalField(max_digits=10,decimal_places=2)
      image=models.ImageField(upload_to='product',blank=True)

      stock=models.IntegerField()
      available=models.BooleanField(default=True)
      created=models.DateTimeField(auto_now_add=True)
      updated=models.DateTimeField(auto_now_add=True)
      size=models.CharField(max_length=3, default='S')

      class Meta:
          ordering=('name',)
          verbose_name='product'
          verbose_name_plural='products'
      def get_url(self):
          return reverse('homepage:ProdCatDetail',args=[self.category.slug,self.slug])
      def __str__(self):
          return self.name

homepage/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
     first_name=forms.CharField(max_length=100,required=True)
     last_name=forms.CharField(max_length=100,required=True)
     email=forms.EmailField(max_length=254,help_text='eg.youremail@anyemail.com')

     class Meta:
         model=User
         fields=('first_name','last_name','email','username','password1','password2')

category/views.py
from django.shortcuts import render,get_object_or_404,redirect
from homepage.models import Category,Product
from django.http import HttpResponse
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.
def category(request):
    return render(request,'category.html')

def prodByCat(request,catname):
    c_page=get_object_or_404(Category,slug=catname)
    products_list=Product.objects.filter(category=c_page,available=True)
    paginator=Paginator(products_list,15)
    products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'products':products})


def ProdCatDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})    

def getAllCat(request):
    products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,15)
    products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'products':products})

homepage/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Category,Product
from django.http import HttpResponse
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from django.contrib.auth.models import Group,User
from .forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login,authenticate,logout


# Create your views here.
def home(request):

    products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
         products=paginator.page(paginator.num_pages)
    return render(request,'home.html',{'products':products})

def signupView(request):
    if request.method=='POST':
        form=SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            signup_user=User.objects.get(username=username)
            customer_group=Group.objects.get(name='Customer')
            customer_group.user_set.add(signup_user)


    else:
        form=SignUpForm()
        return render(request,'accounts/signup.html',{'form':form})

def signinView(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
           username=request.POST['username']
           password=request.POST['password']
           user=authenticate(username=username,password=password)
           if user is not None:
              login(request,user)
           return redirect('homepage:home')

        else:
              return redirect('signup')
    else:
          form=AuthenticationForm()
    return render(request,'accounts/signin.html',{'form':form})

def signoutView(request):
    logout(request)
    return redirect('signin')

homepage/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Little Closet template">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-4.1.2/bootstrap.min.css'%}">
    <link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/flexslider/flexslider.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main_styles.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static  'css/responsive.css'%}">

     {% block css_custums %}{% endblock %}

</head>
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

      {% include 'navbar.html' %}

      <div class="super_container">

        {% include 'header.html' %}
        <div class="super_container_inner">
          <div class="super_overlay"></div>

          {% block content %}
          {% endblock %}
      {% include 'footer.html' %}
       </div>
      </div>


      <script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
      <script src="{% static 'css/bootstrap-4.1.2/popper.js'%}"></script>
      <script src="{% static 'css/bootstrap-4.1.2/bootstrap.min.js'%}"></script>
      <script src="{% static 'plugins/greensock/TweenMax.min.js'%}"></script>
      <script src="{% static 'plugins/greensock/TimelineMax.min.js'%}"></script>
      <script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js'%}"></script>
      <script src="{% static 'plugins/greensock/animation.gsap.min.js'%}"></script>
      <script src="{% static 'plugins/greensock/ScrollToPlugin.min.js'%}"></script>
      <script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js'%}"></script>
      <script src="{% static 'plugins/easing/easing.js'%}"></script>
      <script src="{% static 'plugins/progressbar/progressbar.min.js'%}"></script>
      <script src="{% static 'plugins/parallax-js-master/parallax.min.js'%}"></script>
      <script src="{% static 'plugins/flexslider/jquery.flexslider-min.js'%}"></script>
      <script src="{% static 'js/product.js'%}"></script>
      <script src="{% static 'js/custom.js'%}"></script>


  </body>
</html>

homepage/templates/category.html
  {% extends "base.html" %}
  {% load staticfiles %}
  {% block metadescription %}
    {% if category %}
    {{category.description|truncatewords:155}}
    {% else %}
    welcome to cushion store
    {% endif %}
    {% endblock %}
    {% block title %}
      {% if category %}
      {{category.name}}-perfect cushion store
      {% else %}
      see your cushion store-perfect cushion collection
      {% endif %}
    {% endblock %}
    {% block content %}

  contenttypes

  
  {% endblock %}

homepage/templates/contact.html
<html>
<head>
  <title>hello</title>
  </head>
  <body>
    <h1>
      free size
      </h1>
      </body>
      </html>
      

homepage/templates/footer.html
<!-- Footer -->

<footer class="footer">
  <div class="footer_content">
    <div class="container">
      <div class="row">

        <!-- About -->
        <div class="col-lg-4 footer_col">
          <div class="footer_about">
            <div class="footer_logo">
              <a href="#">

                <div class="d-flex flex-row align-items-center justify-content-start">
                  <div class="footer_logo_icon"><img src="images/logo_2.png" alt=""></div>
                <a href="{% url 'homepage:home' %}"><h2 style="color:black;font-family:Luminari;">Himalaya Collection</h2></a>
                </div>
              </a>
            </div>
            <div class="footer_about_text">
              <p></p>
            </div>
          </div>
        </div>

        <!-- Footer Links -->
        <div class="col-lg-4 footer_col">
          <div class="footer_menu">
            <div class="footer_title">Support</div>
            <ul class="footer_list">
              <li>
                <a href="#"><div>Customer Service<div class="footer_tag_1">online now</div></div></a>
              </li>
              <li>
                <a href=""><div>Return Policy</div></a>
              </li>
              <li>
                <a href="#"><div>Size Guide<div class="footer_tag_2">recommended</div></div></a>
              </li>
              <li>
                <a href="#"><div>Terms and Conditions</div></a>
              </li>
              <li>
                <a href="#"><div>Contact</div></a>
              </li>
            </ul>
          </div>
        </div>

        <!-- Footer Contact -->
        <div class="col-lg-4 footer_col">
          <div class="footer_contact">
            <div class="footer_social">
              <div class="footer_title">Stay in Touch</div>
              <ul class="footer_social_list d-flex flex-row align-items-start justify-content-start">
                <li><a href="http://www.facebook.com"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="http://www.youtube.com"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                <li><a href="http://www.google.com"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                <li><a href="http://www.instagram.com"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer_bar">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="footer_bar_content d-flex flex-md-row flex-column align-items-center justify-content-start">
            <div class="copyright order-md-1 order-2"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
<!--<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
            <!--<nav class="footer_nav ml-md-auto order-md-2 order-1">
              <ul class="d-flex flex-row align-items-center justify-content-start">
                <li><a href="category.html">Women</a></li>
                <li><a href="category.html">Men</a></li>
                <li><a href="category.html">Kids</a></li>
                <li><a href="category.html">Home Deco</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
            </nav>-->
          <marquee  <h1 style="color:black;font-family:Luminari;">Himalaya Collection</h1></marquee>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

homepage/templates/header.html
{% load staticfiles %}
<!-- Header -->

<header class="header">
  <div class="header_overlay"></div>
  <div class="header_content d-flex flex-row align-items-center justify-content-start">
    <div class="logo">
      <a href="#">
        <div class="d-flex flex-row align-items-center justify-content-start">
          <div><img src="{% static 'img/logo_1.png'%}" alt=""></div>
          <a href="{% url 'homepage:home' %}"><h2 style="color:black;font-family:Luminari;">Himalaya Collection</h2></a>
        </div>
      </a>
    </div>
    <div class="hamburger"><i class="fa fa-bars" aria-hidden="true"></i></div>
    <nav class="main_nav">
      <ul class="d-flex flex-row align-items-start justify-content-start">
        <li class="active"><a href="#">Women</a></li>
        <li><a href="#">Men</a></li>
        <li><a href="#">Kids</a></li>
        <li><a href="#">Home Deco</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </nav>
    <div class="header_right d-flex flex-row align-items-center justify-content-start ml-auto">
      <!-- Search -->
      <div class="sert">
      <form class="form-inline my-2 my-lg-0"action="{% url 'search_app:searchResult' %}",method="get">
        {% csrf_token%}
        <input type="search" class="search_input" placeholder="Search" required="required" aria-label="Search" name="q" style="align:center; width:500px;
                  -webkit-transition: width 0.4s ease-in-out;transition: width 0.4s ease-in-out;">

  			<button class="menu_search_button"><img src="{% static 'img/search.png'%}" alt="" > </button>
      </form>
      </div>
      <!-- User -->
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

     {% if request.user.is_authenticated and request.user.first_name %}

            welcome,<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{request.user.first_name}}
              <i class="fas fa-user-circle">
                </i></a>

              <a href="{%url 'signout'%}"> Sign Out <i class ="fas fa-sign-out-alt"></i></a>
              {% else %}

&nbsp;&nbsp;&nbsp;

                  <a href="{%url 'signup'%}"> signup<i class="fas-fa-user-plus"></i></a>
&nbsp;&nbsp;&nbsp;

                    <a href="{% url 'signin'%}"> <img src="{% static 'img/user.svg'%}" style="width:30px; height:30px;"</a>

                    {% endif %}


      {%if item_count >= 0 %}
         <a class="nav-link" href="{% url 'cart:cart_detail'%}"> <img  src="{% static 'img/cart.svg'%}"  style="width:30px; height:30px;">{{item_count}}</a>
       {% endif %}

      <div class="header_phone d-flex flex-row align-items-center justify-content-start">
        <div><div><img src="{% static 'img/phone.svg'%}" alt="https://www.flaticon.com/authors/freepik"></div></div>
        <div>+1 912-252-7350</div>
      </div>
    </div>
  </div>
</header>

homepage/templates/navbar.html
{% load staticfiles %}
<!-- Menu -->

<div class="menu">

	<!-- Search -->

	<!-- Navigation -->
	<div class="menu_nav">
		<ul>
				
			{% for cat in links %}
<li><a href="{% url 'category:products_by_category' cat.slug %}">{{cat.name}}</a></li>
{% endfor %}

		</ul>
	</div>
	<!-- Contact Info -->
	<div class="menu_contact">
		<div class="menu_phone d-flex flex-row align-items-center justify-content-start">
			<div><div><img src="{% static 'img/phone.svg'%}" alt="https://www.flaticon.com/authors/freepik"></div></div>
			<div>+1 912-252-7350</div>
		</div>
		<div class="menu_social">
			<ul class="menu_social_list d-flex flex-row align-items-start justify-content-start">
				<li><a href="http://www.facebook.com"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="http://www.youtube.com"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
				<li><a href="http://www.google.com"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
				<li><a href="http://www.instagram.com"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</div>
</div>

homepage/templates/signup.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags%}
{% block metadescription %}
  Sign up to new account with us.
  {% endblock %}
  {% block title %}
    Create  a new account

  {% endblock %}
  {%block content %}

  <div>
    {% if not form.is_valid %}
    <div class="mx-auto">
      <br>
      <h1 class="my_title text-center">Create a new account </h1>
      <br>
      <div class="col-9 col-sm-9 col-md-6 col-lg-5 mx-auto bg-light">
        <br>
        <p>Enter the following information to create a nfw account</p>
        <form method="post">
          {% csrf_token%}
          <p>{{form | crispy }}</p>
          <button type="submit" class="btn btn-secondary">Register account</button>
          </form>
          <br>
          </div>
          </div>
          {%else%}
          <div class="mx-auto">
            <br>
            <h1 class="my_title text-center">Your account has been successfully created</h1>
            <br>
            <div>
              <p> Dear Customer,
                <br>
                your account has been created and it is ready to use .
                <br>
                <a href="{% url 'homepage:allProdCat'%}">continue shopping </a>and enjoy the variety of clothes
                </p>
                </div>
                </div>
                {% endif %}
                </div>
                <br>
                {% endblock%}

homepage/templates/top-navbar.html
<div class="container">
   <div class="my_custom_menu">
     {% if request.user.is_authenticated and request.user.first_name %}

            welcome,<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{request.user.first_name}}
              <i class="fas fa-user-circle">
                </i></a>

              <a href="{%url 'signout'%}"> Sign Out <i class ="fas fa-sign-out-alt"></i></a>
              {% else %}

&nbsp;&nbsp;&nbsp;

                  <a href="{%url 'signup'%}"> Sign Out<i class="fas-fa-user-plus"></i></a>
&nbsp;&nbsp;&nbsp;

                    <a href="{% url 'signin'%}"> Sign in <i class="fas-fa-sign-in-alt"></i></a>

                    {% endif %}

</div>
</div>