cart/urls.py
from django.urls import path
from .import views
app_name='cart'

urlpatterns=[
path('add/<int:product_id>/',views.add_cart,name="add_cart"),
path('',views.cart_detail,name="cart_detail"),
path('cart_remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
path('full_remove/<int:product_id>/',views.full_remove,name="full_remove"),



]

category/urls.py
from django.urls import path
from category import views
app_name='category'

urlpatterns=[
 path('',views.getAllCat,name='category'),
 path('<slug:catname>',views.prodByCat,name='products_by_category'),
 ]

homepage/urls.py
from django.urls import path
from homepage import views
app_name='homepage'

urlpatterns=[
 path('',views.home,name='home')
]

myfashion/urls.py
from django.contrib import admin
from django.urls import path,include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/',include('homepage.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('category/',include('category.urls')),
    path('product/',include('product.urls')),
    path('account/create/',views.signupView,name='signup'),
    path('account/login/',views.signinView,name='signin'),
    path('account/logout/',views.signoutView,name='signout'),
    


]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product import views
app_name='product'

urlpatterns=[
 path('<slug:prodid>',views.product,name='product'),
 ]

category/views.py
from django.shortcuts import render,get_object_or_404,redirect
from homepage.models import Category,Product
from django.http import HttpResponse
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.
def category(request):
    return render(request,'category.html')

def prodByCat(request,catname):
    c_page=get_object_or_404(Category,slug=catname)
    products_list=Product.objects.filter(category=c_page,available=True)
    paginator=Paginator(products_list,15)
    products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'products':products})


def ProdCatDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})    

def getAllCat(request):
    products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,15)
    products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'products':products})

category/templates/category.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css_custums %}
<link rel="stylesheet" type="text/css" href="{% static  'css/category.css' %}">
<link rel="stylesheet" type="text/css" href="{% static  'css/category_responsive.css' %}">
{% endblock %}
  {% block content %}

  <div class="home">
			<div class="home_container d-flex flex-column align-items-center justify-content-end" >
				<div class="home_content text-center">
					<div class="home_title">Best Sellers</div>
					<div class="breadcrumbs d-flex flex-column align-items-center justify-content-center">
						<ul class="d-flex flex-row align-items-start justify-content-start text-center">
							<li><a href="{% url 'homepage:home' %}">Home</a></li>
							<li><a href="{% url 'category:products_by_category' 'bags' %}">Woman</a></li>

						</ul>
					</div>
				</div>
			</div>
		</div>


		<!-- Products -->
		<div class="products">
			<div class="container">
				<div class="row products_bar_row">
					<div class="col">
						<div class="products_bar d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-lg-start justify-content-center">
							<div class="products_bar_links">
								<ul class="d-flex flex-row align-items-start justify-content-start">
                  {% for cat in links %}
                  <a class="dropdown-item" href="{% url 'category:products_by_category' cat.slug %}">{{cat.name}}</a>
               {% endfor %}
								</ul>
							</div>
							<div class="products_bar_side d-flex flex-row align-items-center justify-content-start ml-lg-auto">
								<div class="products_dropdown product_dropdown_sorting">
									<div class="isotope_sorting_text"><span>Default Sorting</span><i class="fa fa-caret-down" aria-hidden="true"></i></div>
									<ul>
										<li class="item_sorting_btn" data-isotope-option='{ "sortBy": "original-order" }'>Default</li>
										<li class="item_sorting_btn" data-isotope-option='{ "sortBy": "price" }'>Price</li>
										<li class="item_sorting_btn" data-isotope-option='{ "sortBy": "name" }'>Name</li>
									</ul>
								</div>
								<div class="product_view d-flex flex-row align-items-center justify-content-start">
									<div class="view_item active"><img src="{% static 'img/view_1.png" alt=""></div>
									<div class="view_item"><img src="{% static 'img/view_2.png' %}" alt=""></div>
									<div class="view_item"><img src="{% static 'img/view_3.png' %}" alt=""></div>
								</div>
								<div class="products_dropdown text-right product_dropdown_filter">
									<div class="isotope_filter_text"><span>Filter</span><i class="fa fa-caret-down" aria-hidden="true"></i></div>
									<ul>

										<li class="item_filter_btn" data-filter="*">All</li>
										<li class="item_filter_btn" data-filter=".hot">Hot</li>
										<li class="item_filter_btn" data-filter=".new">New</li>
										<li class="item_filter_btn" data-filter=".sale">Sale</li>
									</ul>
								</div>

							</div>
						</div>
					</div>
				</div>
				<div class="row products_row products_container grid">


{% for product in products.object_list %}
					<!-- Product -->
					<div class="col-xl-4 col-md-6 grid-item new">
						<div class="product">
							<div class="product_image"><a href="{% url 'product:product' product.slug %}"><img src="{{product.image.url}}" style="width:350px;height:400px;" alt="" style=""></a></div>

								<div class="product_info d-flex flex-row align-items-start justify-content-start">
									<div>
										<div>
											<div class="product_name"><a href="{% url 'product:product' product.slug %}">{{product.name}}</a></div>
											<div class="product_category">In <a href="category.html">{{product.category}}</a></div>
										</div>
									</div>
									<div class="ml-auto text-right">
										<div class="rating_r rating_r_4 home_item_rating"><i></i><i></i><i></i><i></i><i></i></div>
										<div class="product_price text-right">{{product.price}}</div>
									</div>
								</div>
								<div class="product_buttons">
									<div class="text-right d-flex flex-row align-items-start justify-content-start">
										<div class="product_button product_fav text-center d-flex flex-column align-items-center justify-content-center">
											<div><div><img src="{% static 'img/heart_2.svg' %}" class="svg" alt=""><div>+</div></div></div>
										</div>
                    <div class="product_button product_cart text-center d-flex flex-column align-items-center justify-content-center">
  										<div><div><a href="{% url 'cart:add_cart' product.id %}"><img src="{% static 'img/cart.svg' %}" class="svg"  style="color:black;" alt=""><div>+</div></div></div>
  									</div>
									</div>
								</div>

						</div>
					</div>

      {% endfor %}

					<!-- Product

				</div>
				<div class="row page_nav_row">
					<div class="col">
						<div class="page_nav">
							<ul class="d-flex flex-row align-items-start justify-content-center">
								<li class="active"><a href="#">01</a></li>
								<li><a href="">02</a></li>
								<li><a href="#">03</a></li>
								<li><a href="#">04</a></li>
							</ul>
						</div>
					</div>
				</div> -->
			</div>
    </div>
      {% endblock %}